---
# Playbook starts the bhft role which is designed to meet the requirements of the test task.
# let's go
- hosts: test_ubuntu
  become: True
  become_method: sudo
  roles:
    - name: bhft
      tags: luks
  tasks:
    - name: rename network interface
      block:
        - name: change netplan file
          lineinfile:
            path: /etc/netplan/50-cloud-init.yaml
            regexp: '^      set-name:\ \"enX0\"$'
            line: '      set-name: "net0"'
            validate: netplan try %s
            backup: True
          register: rename
        - name: apply new configuration
          shell: netplan apply        
          when: rename.changed
        - name: print
          debug:
            msg: "interface enX0 was successfully renamed to net0"
          when: rename.changed
      tags: rename_int    
    - name: cpu governor
      shell: echo performance | tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor
      tags: governor
    - name: print cores
      debug:
        msg: " number of cpu core: {{ ansible_processor_vcpus }}, number of threads per core: {{ ansible_processor_threads_per_core }}"    
      tags: print_cores




...
